# USE THIS FILE ONLY AS A REFERENCE FOR FURTHER DEVELOPMENT
services:
  aegis_gym:
    image: ghcr.io/agh-ceai/aegis_gym:v0.0.1-hardware
    container_name: aegis_gym
    volumes:
      - ~/clearml.conf:/root/clearml.conf:ro
    stdin_open: true
    tty: true
    environment:
      - CLEARML_CONFIG_FILE=/ws/clearml.conf
    profiles:
      - hardware
