env:
    num_envs: 10
    num_obs: 18
    num_actions: 6
    action_max_linear_speed: 0.098  # m/s
    action_max_angular_speed: 0.1  # rad/s
    episode_length_s: 8.0
    max_steps: null
    ctrl_dt: 0.004  # 1 / 250 Hz (RTDE protocol freq), original 0.01
    policy_dt: 0.04  # 1 / 25 Hz, used to calculate number of steps
    box_size_default: [0.03, 0.08, 0.06]
    box_size_symmetrical: [0.0283, 0.0283, 0.1005]
    table_size: [0.55, 0.84, 0.818]
    workbench_size: [0.64, 1.0, 0.821]
    box_collision: False
    box_fixed: True
    t_block_scale: 1.0
    image_resolution: [64, 64]
    use_rasterizer: True
    visualize_camera: False
    visualize_cell: True
    cameras_setup: "default"
    reward_scales:
        reach: 0.3
        position: 1.0
        orientation: 0.5
        success: 2.0
