logger: "clearml"
neptune_project: "TEST_PLAYGROUND/aegis_grasp"
wandb_project: "TEST_PLAYGROUND/aegis_grasp"
clearml_project: "TEST_PLAYGROUND/aegis_grasp"
clearml_log_cfg_as_hyperparams: False
local_log_dir: ""
