on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      # TODO(issue#52) reactive automatic tests
      # - name: Run tests
      #   run: poetry run pytest -v -s

      - name: Build package
        run: poetry build
